import type { FuelProductKey } from '@tranhanh/shared';
import type { Locale } from '../i18n/routes';
const vi = {
  eyebrow: 'GIÁ TỐI ĐA · NGUỒN CHÍNH THỨC',
  title: 'Giá xăng hôm nay',
  intro: 'Mức giá bán lẻ tối đa hiện hành do Bộ Công Thương công bố theo kỳ điều hành.',
  current: 'Giá hiện hành',
  previous: 'Giá trước',
  increase: 'Tăng',
  decrease: 'Giảm',
  unchanged: 'Không đổi',
  applied: 'Áp dụng từ',
  updated: 'Cập nhật dữ liệu',
  history: 'Lịch sử điều chỉnh',
  source: 'Nguồn',
  publication: 'Văn bản',
  published: 'Công bố',
  semantics: 'Giá bán lẻ tối đa',
  stale: 'Dữ liệu gần nhất được đối chiếu lúc',
  degraded: 'Lần cập nhật gần nhất gặp sự cố; đang hiển thị dữ liệu tốt gần nhất.',
  noData: 'Chưa có dữ liệu giá đã được xác minh.',
  unavailable: 'Dịch vụ dữ liệu giá nhiên liệu tạm thời không khả dụng.',
  price: 'Mức giá',
  change: 'Thay đổi',
  product: 'Sản phẩm',
  effective: 'Hiệu lực',
  openSource: 'Mở nguồn chính thức',
  perLiter: 'đồng/lít',
  perKg: 'đồng/kg',
  maximumNote: 'Đây là mức không cao hơn do cơ quan quản lý công bố, không phải giá thời gian thực tại từng cửa hàng.',
  products: {
    'e5-ron-92': 'Xăng E5RON92',
    'e10-ron-95-iii': 'Xăng E10RON95-III',
    'diesel-0-05s': 'Dầu điêzen 0.05S',
    'mazut-180cst-3-5s': 'Dầu madút 180CST 3.5S',
  } as Record<FuelProductKey, string>,
};
const en: typeof vi = {
  eyebrow: 'MAXIMUM PRICES · OFFICIAL SOURCE',
  title: 'Fuel Prices in Vietnam',
  intro:
    'Current applicable maximum retail prices published for each adjustment period by the Ministry of Industry and Trade.',
  current: 'Current price',
  previous: 'Previous price',
  increase: 'Increase',
  decrease: 'Decrease',
  unchanged: 'Unchanged',
  applied: 'Effective from',
  updated: 'Data retrieved',
  history: 'Recent adjustment history',
  source: 'Source',
  publication: 'Publication',
  published: 'Published',
  semantics: 'Maximum retail price',
  stale: 'The latest data was checked at',
  degraded: 'The latest update attempt failed; the last known good data remains visible.',
  noData: 'No verified fuel-price data is available yet.',
  unavailable: 'The fuel-price data service is temporarily unavailable.',
  price: 'Price',
  change: 'Change',
  product: 'Product',
  effective: 'Effective',
  openSource: 'Open official source',
  perLiter: 'VND/liter',
  perKg: 'VND/kg',
  maximumNote: 'These are regulatory maximum prices, not real-time prices at individual stations.',
  products: {
    'e5-ron-92': 'E5 RON 92 gasoline',
    'e10-ron-95-iii': 'E10 RON 95-III gasoline',
    'diesel-0-05s': 'Diesel 0.05S',
    'mazut-180cst-3-5s': 'Mazut 180CST 3.5S',
  },
};
export const fuelPriceCopy = (locale: Locale) => (locale === 'vi' ? vi : en);
